version: '2'
services:
  app:
    image: docker.io/bitnami/codeigniter:3
    ports:
      - '8000'
    environment:
      - CODEIGNITER_PROJECT_NAME=app
    volumes:
      - '.:/app:rw'
    depends_on:
      - mariadb
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
